/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTAddition extends org.eclipse.xtext.astconversion.ast.ASTSequence {
	public ASTAddition(){}
	public ASTAddition(String left, String right){
		this.left = left;
		this.right = right;
	}
	
	public String left;
	public String right;
}
