/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTAddition extends org.eclipse.xtext.astconversion.ast.ASTSequence {
	public ASTAddition(){}
	public ASTAddition(String left, String right, java.util.List<org.eclipse.xtext.astconversion.ast.ASTSequence> expressions){
		this.left = left;
		this.right = right;
		this.expressions = expressions;
	}
	
	public String left;
	public String right;
	public java.util.List<org.eclipse.xtext.astconversion.ast.ASTSequence> expressions;
}
