/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTAutoExplicitClass extends org.eclipse.xtext.astconversion.ast.ASTEntry {
	public ASTAutoExplicitClass(){}
	public ASTAutoExplicitClass(String name2){
		this.name2 = name2;
	}
	
	public String name2;
}
