/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTHoistingActionNewX extends org.eclipse.xtext.astconversion.ast.ASTHoistingActionNew {
	public ASTHoistingActionNewX(){}
	public ASTHoistingActionNewX(String value){
		this.value = value;
	}
	
	public String value;
}
