/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTMapEntryCustom {
	public ASTMapEntryCustom(){}
	public ASTMapEntryCustom(String x, String y){
		this.x = x;
		this.y = y;
	}
	
	public String x;
	public String y;
}
