/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTMapEntry {
	public ASTMapEntry(){}
	public ASTMapEntry(String x, int y){
		this.x = x;
		this.y = y;
	}
	
	public String x;
	public int y;
}
