/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTOther implements org.eclipse.xtext.astconversion.ast.ASTEntry {
	public ASTOther(){}
	public ASTOther(String name, Object content){
		this.name = name;
		this.content = content;
	}
	
	public String name;
	public Object content;
}
