/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTProgram {
	public ASTProgram(){}
	public ASTProgram(java.util.List<org.eclipse.xtext.astconversion.ast.ASTSequence> sequence, java.util.List<org.eclipse.xtext.astconversion.ast.ASTEntry> entries, ASTLists list){
		this.sequence = sequence;
		this.entries = entries;
		this.list = list;
	}
	
	public java.util.List<org.eclipse.xtext.astconversion.ast.ASTSequence> sequence;
	public java.util.List<org.eclipse.xtext.astconversion.ast.ASTEntry> entries;
	public ASTLists list;
}
