/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTReturnsNewX {
	public ASTReturnsNewX(){}
	public ASTReturnsNewX(String value){
		this.value = value;
	}
	
	public String value;
}
