/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTReference {
	public ASTReference(){}
	public ASTReference(String name){
		this.name = name;
	}
	
	public String name;
}
