/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTSequence {
	public ASTSequence(){}
	public ASTSequence(java.util.List<org.eclipse.xtext.astconversion.ast.ASTSequence> expressions){
		this.expressions = expressions;
	}
	
	public java.util.List<org.eclipse.xtext.astconversion.ast.ASTSequence> expressions;
}
