/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTX implements org.eclipse.xtext.astconversion.ast.ASTHoistingAlternative {
	public ASTX(){}
	public ASTX(String val){
		this.val = val;
	}
	
	public String val;
}
