/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.ast;


public class ASTY implements org.eclipse.xtext.astconversion.ast.ASTHoistingAlternative {
	public ASTY(){}
	public ASTY(String val, String y){
		this.val = val;
		this.y = y;
	}
	
	public String val;
	public String y;
}
