/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.xtext.astconversion.astConversionSimple.ActionNew;
import org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Action New</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ActionNewImpl extends MinimalEObjectImpl.Container implements ActionNew
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ActionNewImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AstConversionSimplePackage.Literals.ACTION_NEW;
  }

} //ActionNewImpl
