/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage;
import org.eclipse.xtext.astconversion.astConversionSimple.ManualClass;
import org.eclipse.xtext.astconversion.astConversionSimple.Reference;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Manual Class</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ManualClassImpl#getRef3 <em>Ref3</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ManualClassImpl#getName3 <em>Name3</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ManualClassImpl extends EntryImpl implements ManualClass
{
  /**
   * The cached value of the '{@link #getRef3() <em>Ref3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRef3()
   * @generated
   * @ordered
   */
  protected Reference ref3;

  /**
   * The default value of the '{@link #getName3() <em>Name3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName3()
   * @generated
   * @ordered
   */
  protected static final String NAME3_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName3() <em>Name3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName3()
   * @generated
   * @ordered
   */
  protected String name3 = NAME3_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ManualClassImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AstConversionSimplePackage.Literals.MANUAL_CLASS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Reference getRef3()
  {
    return ref3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRef3(Reference newRef3, NotificationChain msgs)
  {
    Reference oldRef3 = ref3;
    ref3 = newRef3;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AstConversionSimplePackage.MANUAL_CLASS__REF3, oldRef3, newRef3);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRef3(Reference newRef3)
  {
    if (newRef3 != ref3)
    {
      NotificationChain msgs = null;
      if (ref3 != null)
        msgs = ((InternalEObject)ref3).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AstConversionSimplePackage.MANUAL_CLASS__REF3, null, msgs);
      if (newRef3 != null)
        msgs = ((InternalEObject)newRef3).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AstConversionSimplePackage.MANUAL_CLASS__REF3, null, msgs);
      msgs = basicSetRef3(newRef3, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AstConversionSimplePackage.MANUAL_CLASS__REF3, newRef3, newRef3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName3()
  {
    return name3;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName3(String newName3)
  {
    String oldName3 = name3;
    name3 = newName3;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AstConversionSimplePackage.MANUAL_CLASS__NAME3, oldName3, name3));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AstConversionSimplePackage.MANUAL_CLASS__REF3:
        return basicSetRef3(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AstConversionSimplePackage.MANUAL_CLASS__REF3:
        return getRef3();
      case AstConversionSimplePackage.MANUAL_CLASS__NAME3:
        return getName3();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AstConversionSimplePackage.MANUAL_CLASS__REF3:
        setRef3((Reference)newValue);
        return;
      case AstConversionSimplePackage.MANUAL_CLASS__NAME3:
        setName3((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AstConversionSimplePackage.MANUAL_CLASS__REF3:
        setRef3((Reference)null);
        return;
      case AstConversionSimplePackage.MANUAL_CLASS__NAME3:
        setName3(NAME3_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AstConversionSimplePackage.MANUAL_CLASS__REF3:
        return ref3 != null;
      case AstConversionSimplePackage.MANUAL_CLASS__NAME3:
        return NAME3_EDEFAULT == null ? name3 != null : !NAME3_EDEFAULT.equals(name3);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name3: ");
    result.append(name3);
    result.append(')');
    return result.toString();
  }

} //ManualClassImpl
