/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.astconversion.parser.antlr.internal.InternalASTConversionSimpleParser;
import org.eclipse.xtext.astconversion.services.ASTConversionSimpleGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ASTConversionSimpleParser extends AbstractAntlrParser {

	@Inject
	private ASTConversionSimpleGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalASTConversionSimpleParser createParser(XtextTokenStream stream) {
		return new InternalASTConversionSimpleParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public ASTConversionSimpleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ASTConversionSimpleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
