/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ASTConversionSimpleAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/xtext/astconversion/parser/antlr/internal/InternalASTConversionSimple.tokens");
	}
}
