grammar org.eclipse.xtext.astconversion.ASTConversionSimple with org.eclipse.xtext.common.Terminals

generate astConversionSimple "http://www.xtext.org/example/ASTConversionSimple"

Program becomes:
	(entries+=Entry)+
	(sequence+=Sequence)+;

Entry becomes:
	AutoClass | AutoExplicitClass | ManualClass | CustomASTClass | CustomCopyASTClass | Other | Element;

AutoClass becomes:
	"auto" ref=Reference name=ID ";";

AutoExplicitClass becomes (name):
	"auto-explicit" ref=Reference name=ID ";";

ManualClass becomes («ASTReference» ref, String value) $$
	this.ref = children.ref;
	this.value = node.getName();
$$:
	"manual" ref=Reference name=ID ";";

CustomASTClass becomes ASTCustomClass $$
	this.type = children.ref.name;
	this.name = node.getName();
$$:
	"custom" ref=Reference name=ID ";";
	
CustomCopyASTClass becomes ASTCustomClass(name) $$
	this.type = children.ref.name;
$$:
	"custom-copy" ref=Reference name=ID ";";

Reference becomes:
	name=ID;

// --------
	
Other becomes:
	"other" name=ID content=(Reference | AutoClass)
;

// --------

Element becomes:
	'element' name=ID (type=ChangeKind)? '=' (value+=ChangeKind)+ ';';

enum ChangeKind becomes:
	ADD='add' | MOVE='move' |
	REMOVE='remove';

// --------

Sequence becomes: "sequence" Addition ( {Sequence.expressions+=current} expressions+=Addition)* ";";

Addition becomes: 
	left=ID '+' right=ID;
