/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage
 * @generated
 */
public interface AstConversionSimpleFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AstConversionSimpleFactory eINSTANCE = org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimpleFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Program</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Program</em>'.
   * @generated
   */
  Program createProgram();

  /**
   * Returns a new object of class '<em>Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Entry</em>'.
   * @generated
   */
  Entry createEntry();

  /**
   * Returns a new object of class '<em>Auto Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Auto Class</em>'.
   * @generated
   */
  AutoClass createAutoClass();

  /**
   * Returns a new object of class '<em>Auto Explicit Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Auto Explicit Class</em>'.
   * @generated
   */
  AutoExplicitClass createAutoExplicitClass();

  /**
   * Returns a new object of class '<em>Manual Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Manual Class</em>'.
   * @generated
   */
  ManualClass createManualClass();

  /**
   * Returns a new object of class '<em>Custom AST Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Custom AST Class</em>'.
   * @generated
   */
  CustomASTClass createCustomASTClass();

  /**
   * Returns a new object of class '<em>Custom Copy AST Class</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Custom Copy AST Class</em>'.
   * @generated
   */
  CustomCopyASTClass createCustomCopyASTClass();

  /**
   * Returns a new object of class '<em>Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reference</em>'.
   * @generated
   */
  Reference createReference();

  /**
   * Returns a new object of class '<em>Other</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Other</em>'.
   * @generated
   */
  Other createOther();

  /**
   * Returns a new object of class '<em>Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Element</em>'.
   * @generated
   */
  Element createElement();

  /**
   * Returns a new object of class '<em>Sequence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sequence</em>'.
   * @generated
   */
  Sequence createSequence();

  /**
   * Returns a new object of class '<em>Addition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Addition</em>'.
   * @generated
   */
  Addition createAddition();

  /**
   * Returns a new object of class '<em>Returns New X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Returns New X</em>'.
   * @generated
   */
  ReturnsNewX createReturnsNewX();

  /**
   * Returns a new object of class '<em>Action New</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action New</em>'.
   * @generated
   */
  ActionNew createActionNew();

  /**
   * Returns a new object of class '<em>Lists</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lists</em>'.
   * @generated
   */
  Lists createLists();

  /**
   * Returns a new object of class '<em>Map Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Entry</em>'.
   * @generated
   */
  MapEntry createMapEntry();

  /**
   * Returns a new object of class '<em>Map Entry Custom</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Entry Custom</em>'.
   * @generated
   */
  MapEntryCustom createMapEntryCustom();

  /**
   * Returns a new object of class '<em>Map Entry Custom2</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Map Entry Custom2</em>'.
   * @generated
   */
  MapEntryCustom2 createMapEntryCustom2();

  /**
   * Returns a new object of class '<em>Hoisting Alternative</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hoisting Alternative</em>'.
   * @generated
   */
  HoistingAlternative createHoistingAlternative();

  /**
   * Returns a new object of class '<em>X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>X</em>'.
   * @generated
   */
  X createX();

  /**
   * Returns a new object of class '<em>Y</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Y</em>'.
   * @generated
   */
  Y createY();

  /**
   * Returns a new object of class '<em>Hoisting Action New</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hoisting Action New</em>'.
   * @generated
   */
  HoistingActionNew createHoistingActionNew();

  /**
   * Returns a new object of class '<em>Action New X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action New X</em>'.
   * @generated
   */
  ActionNewX createActionNewX();

  /**
   * Returns a new object of class '<em>Hoisting Action New X</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Hoisting Action New X</em>'.
   * @generated
   */
  HoistingActionNewX createHoistingActionNewX();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  AstConversionSimplePackage getAstConversionSimplePackage();

} //AstConversionSimpleFactory
