/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimpleFactory
 * @model kind="package"
 * @generated
 */
public interface AstConversionSimplePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "astConversionSimple";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/ASTConversionSimple";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "astConversionSimple";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  AstConversionSimplePackage eINSTANCE = org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl.init();

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ProgramImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Entries</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__ENTRIES = 0;

  /**
   * The feature id for the '<em><b>Sequence</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__SEQUENCE = 1;

  /**
   * The feature id for the '<em><b>Returns New</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__RETURNS_NEW = 2;

  /**
   * The feature id for the '<em><b>Action New</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__ACTION_NEW = 3;

  /**
   * The feature id for the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__LIST = 4;

  /**
   * The feature id for the '<em><b>Hoisting Alternative</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__HOISTING_ALTERNATIVE = 5;

  /**
   * The feature id for the '<em><b>Hoisting Action New</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__HOISTING_ACTION_NEW = 6;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.EntryImpl <em>Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.EntryImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getEntry()
   * @generated
   */
  int ENTRY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY__NAME = 0;

  /**
   * The number of structural features of the '<em>Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTRY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.AutoClassImpl <em>Auto Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AutoClassImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getAutoClass()
   * @generated
   */
  int AUTO_CLASS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTO_CLASS__NAME = ENTRY__NAME;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTO_CLASS__REF = ENTRY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Auto Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTO_CLASS_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.AutoExplicitClassImpl <em>Auto Explicit Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AutoExplicitClassImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getAutoExplicitClass()
   * @generated
   */
  int AUTO_EXPLICIT_CLASS = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTO_EXPLICIT_CLASS__NAME = ENTRY__NAME;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTO_EXPLICIT_CLASS__REF = ENTRY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Auto Explicit Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AUTO_EXPLICIT_CLASS_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ManualClassImpl <em>Manual Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ManualClassImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getManualClass()
   * @generated
   */
  int MANUAL_CLASS = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANUAL_CLASS__NAME = ENTRY__NAME;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANUAL_CLASS__REF = ENTRY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Manual Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANUAL_CLASS_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.CustomASTClassImpl <em>Custom AST Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.CustomASTClassImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getCustomASTClass()
   * @generated
   */
  int CUSTOM_AST_CLASS = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_AST_CLASS__NAME = ENTRY__NAME;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_AST_CLASS__REF = ENTRY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Custom AST Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_AST_CLASS_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.CustomCopyASTClassImpl <em>Custom Copy AST Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.CustomCopyASTClassImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getCustomCopyASTClass()
   * @generated
   */
  int CUSTOM_COPY_AST_CLASS = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_COPY_AST_CLASS__NAME = ENTRY__NAME;

  /**
   * The feature id for the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_COPY_AST_CLASS__REF = ENTRY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Custom Copy AST Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUSTOM_COPY_AST_CLASS_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ReferenceImpl <em>Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ReferenceImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getReference()
   * @generated
   */
  int REFERENCE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__NAME = 0;

  /**
   * The number of structural features of the '<em>Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.OtherImpl <em>Other</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.OtherImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getOther()
   * @generated
   */
  int OTHER = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER__NAME = ENTRY__NAME;

  /**
   * The feature id for the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER__CONTENT = ENTRY_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Other</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OTHER_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ElementImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__NAME = ENTRY__NAME;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__TYPE = ENTRY_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT__VALUE = ENTRY_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = ENTRY_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.SequenceImpl <em>Sequence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.SequenceImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getSequence()
   * @generated
   */
  int SEQUENCE = 10;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE__EXPRESSIONS = 0;

  /**
   * The number of structural features of the '<em>Sequence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SEQUENCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AdditionImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 11;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__EXPRESSIONS = SEQUENCE__EXPRESSIONS;

  /**
   * The feature id for the '<em><b>Left</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = SEQUENCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = SEQUENCE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = SEQUENCE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ReturnsNewXImpl <em>Returns New X</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ReturnsNewXImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getReturnsNewX()
   * @generated
   */
  int RETURNS_NEW_X = 12;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURNS_NEW_X__VALUE = 0;

  /**
   * The number of structural features of the '<em>Returns New X</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RETURNS_NEW_X_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ActionNewImpl <em>Action New</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ActionNewImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getActionNew()
   * @generated
   */
  int ACTION_NEW = 13;

  /**
   * The number of structural features of the '<em>Action New</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_NEW_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ListsImpl <em>Lists</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ListsImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getLists()
   * @generated
   */
  int LISTS = 14;

  /**
   * The feature id for the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTS__A = 0;

  /**
   * The feature id for the '<em><b>B</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTS__B = 1;

  /**
   * The feature id for the '<em><b>C</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTS__C = 2;

  /**
   * The feature id for the '<em><b>D</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTS__D = 3;

  /**
   * The number of structural features of the '<em>Lists</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTS_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.MapEntryImpl <em>Map Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.MapEntryImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getMapEntry()
   * @generated
   */
  int MAP_ENTRY = 15;

  /**
   * The feature id for the '<em><b>Keys</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_ENTRY__KEYS = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_ENTRY__VALUE = 1;

  /**
   * The number of structural features of the '<em>Map Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_ENTRY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.MapEntryCustomImpl <em>Map Entry Custom</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.MapEntryCustomImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getMapEntryCustom()
   * @generated
   */
  int MAP_ENTRY_CUSTOM = 16;

  /**
   * The feature id for the '<em><b>Keys</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_ENTRY_CUSTOM__KEYS = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_ENTRY_CUSTOM__VALUE = 1;

  /**
   * The number of structural features of the '<em>Map Entry Custom</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAP_ENTRY_CUSTOM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingAlternativeImpl <em>Hoisting Alternative</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingAlternativeImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getHoistingAlternative()
   * @generated
   */
  int HOISTING_ALTERNATIVE = 17;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOISTING_ALTERNATIVE__VAL = 0;

  /**
   * The number of structural features of the '<em>Hoisting Alternative</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOISTING_ALTERNATIVE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.XImpl <em>X</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.XImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getX()
   * @generated
   */
  int X = 18;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int X__VAL = HOISTING_ALTERNATIVE__VAL;

  /**
   * The number of structural features of the '<em>X</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int X_FEATURE_COUNT = HOISTING_ALTERNATIVE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.YImpl <em>Y</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.YImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getY()
   * @generated
   */
  int Y = 19;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y__VAL = HOISTING_ALTERNATIVE__VAL;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y__Y = HOISTING_ALTERNATIVE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Y</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int Y_FEATURE_COUNT = HOISTING_ALTERNATIVE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingActionNewImpl <em>Hoisting Action New</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingActionNewImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getHoistingActionNew()
   * @generated
   */
  int HOISTING_ACTION_NEW = 20;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOISTING_ACTION_NEW__X = 0;

  /**
   * The number of structural features of the '<em>Hoisting Action New</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOISTING_ACTION_NEW_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ActionNewXImpl <em>Action New X</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ActionNewXImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getActionNewX()
   * @generated
   */
  int ACTION_NEW_X = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_NEW_X__VALUE = ACTION_NEW_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Action New X</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_NEW_X_FEATURE_COUNT = ACTION_NEW_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingActionNewXImpl <em>Hoisting Action New X</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingActionNewXImpl
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getHoistingActionNewX()
   * @generated
   */
  int HOISTING_ACTION_NEW_X = 22;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOISTING_ACTION_NEW_X__X = HOISTING_ACTION_NEW__X;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOISTING_ACTION_NEW_X__VALUE = HOISTING_ACTION_NEW_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Hoisting Action New X</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HOISTING_ACTION_NEW_X_FEATURE_COUNT = HOISTING_ACTION_NEW_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind <em>Change Kind</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind
   * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getChangeKind()
   * @generated
   */
  int CHANGE_KIND = 23;


  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getEntries <em>Entries</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Entries</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Program#getEntries()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Entries();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getSequence <em>Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sequence</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Program#getSequence()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Sequence();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getReturnsNew <em>Returns New</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Returns New</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Program#getReturnsNew()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_ReturnsNew();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getActionNew <em>Action New</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Action New</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Program#getActionNew()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_ActionNew();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getList <em>List</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>List</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Program#getList()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_List();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getHoistingAlternative <em>Hoisting Alternative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Hoisting Alternative</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Program#getHoistingAlternative()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_HoistingAlternative();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getHoistingActionNew <em>Hoisting Action New</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Hoisting Action New</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Program#getHoistingActionNew()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_HoistingActionNew();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.Entry <em>Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entry</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Entry
   * @generated
   */
  EClass getEntry();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.Entry#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Entry#getName()
   * @see #getEntry()
   * @generated
   */
  EAttribute getEntry_Name();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.AutoClass <em>Auto Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Auto Class</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AutoClass
   * @generated
   */
  EClass getAutoClass();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.AutoClass#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AutoClass#getRef()
   * @see #getAutoClass()
   * @generated
   */
  EReference getAutoClass_Ref();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.AutoExplicitClass <em>Auto Explicit Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Auto Explicit Class</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AutoExplicitClass
   * @generated
   */
  EClass getAutoExplicitClass();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.AutoExplicitClass#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AutoExplicitClass#getRef()
   * @see #getAutoExplicitClass()
   * @generated
   */
  EReference getAutoExplicitClass_Ref();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.ManualClass <em>Manual Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Manual Class</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ManualClass
   * @generated
   */
  EClass getManualClass();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.ManualClass#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ManualClass#getRef()
   * @see #getManualClass()
   * @generated
   */
  EReference getManualClass_Ref();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass <em>Custom AST Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Custom AST Class</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass
   * @generated
   */
  EClass getCustomASTClass();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass#getRef()
   * @see #getCustomASTClass()
   * @generated
   */
  EReference getCustomASTClass_Ref();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomCopyASTClass <em>Custom Copy AST Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Custom Copy AST Class</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.CustomCopyASTClass
   * @generated
   */
  EClass getCustomCopyASTClass();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomCopyASTClass#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ref</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.CustomCopyASTClass#getRef()
   * @see #getCustomCopyASTClass()
   * @generated
   */
  EReference getCustomCopyASTClass_Ref();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.Reference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Reference
   * @generated
   */
  EClass getReference();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.Reference#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Reference#getName()
   * @see #getReference()
   * @generated
   */
  EAttribute getReference_Name();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.Other <em>Other</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Other</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Other
   * @generated
   */
  EClass getOther();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.Other#getContent <em>Content</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Content</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Other#getContent()
   * @see #getOther()
   * @generated
   */
  EReference getOther_Content();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.Element#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Element#getType()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Type();

  /**
   * Returns the meta object for the attribute list '{@link org.eclipse.xtext.astconversion.astConversionSimple.Element#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Value</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Element#getValue()
   * @see #getElement()
   * @generated
   */
  EAttribute getElement_Value();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.Sequence <em>Sequence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sequence</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Sequence
   * @generated
   */
  EClass getSequence();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.astconversion.astConversionSimple.Sequence#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Sequence#getExpressions()
   * @see #getSequence()
   * @generated
   */
  EReference getSequence_Expressions();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Left</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Left();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Right</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Right();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.ReturnsNewX <em>Returns New X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Returns New X</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ReturnsNewX
   * @generated
   */
  EClass getReturnsNewX();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.ReturnsNewX#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ReturnsNewX#getValue()
   * @see #getReturnsNewX()
   * @generated
   */
  EAttribute getReturnsNewX_Value();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.ActionNew <em>Action New</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action New</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ActionNew
   * @generated
   */
  EClass getActionNew();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.Lists <em>Lists</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lists</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Lists
   * @generated
   */
  EClass getLists();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.Lists#getA <em>A</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>A</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Lists#getA()
   * @see #getLists()
   * @generated
   */
  EReference getLists_A();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.Lists#getB <em>B</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>B</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Lists#getB()
   * @see #getLists()
   * @generated
   */
  EReference getLists_B();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.astconversion.astConversionSimple.Lists#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>C</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Lists#getC()
   * @see #getLists()
   * @generated
   */
  EReference getLists_C();

  /**
   * Returns the meta object for the containment reference list '{@link org.eclipse.xtext.astconversion.astConversionSimple.Lists#getD <em>D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>D</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Lists#getD()
   * @see #getLists()
   * @generated
   */
  EReference getLists_D();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.MapEntry <em>Map Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map Entry</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.MapEntry
   * @generated
   */
  EClass getMapEntry();

  /**
   * Returns the meta object for the attribute list '{@link org.eclipse.xtext.astconversion.astConversionSimple.MapEntry#getKeys <em>Keys</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keys</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.MapEntry#getKeys()
   * @see #getMapEntry()
   * @generated
   */
  EAttribute getMapEntry_Keys();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.MapEntry#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.MapEntry#getValue()
   * @see #getMapEntry()
   * @generated
   */
  EAttribute getMapEntry_Value();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.MapEntryCustom <em>Map Entry Custom</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Map Entry Custom</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.MapEntryCustom
   * @generated
   */
  EClass getMapEntryCustom();

  /**
   * Returns the meta object for the attribute list '{@link org.eclipse.xtext.astconversion.astConversionSimple.MapEntryCustom#getKeys <em>Keys</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Keys</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.MapEntryCustom#getKeys()
   * @see #getMapEntryCustom()
   * @generated
   */
  EAttribute getMapEntryCustom_Keys();

  /**
   * Returns the meta object for the containment reference '{@link org.eclipse.xtext.astconversion.astConversionSimple.MapEntryCustom#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.MapEntryCustom#getValue()
   * @see #getMapEntryCustom()
   * @generated
   */
  EReference getMapEntryCustom_Value();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.HoistingAlternative <em>Hoisting Alternative</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hoisting Alternative</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.HoistingAlternative
   * @generated
   */
  EClass getHoistingAlternative();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.HoistingAlternative#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.HoistingAlternative#getVal()
   * @see #getHoistingAlternative()
   * @generated
   */
  EAttribute getHoistingAlternative_Val();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.X <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>X</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.X
   * @generated
   */
  EClass getX();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.Y <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Y</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Y
   * @generated
   */
  EClass getY();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.Y#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.Y#getY()
   * @see #getY()
   * @generated
   */
  EAttribute getY_Y();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.HoistingActionNew <em>Hoisting Action New</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hoisting Action New</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.HoistingActionNew
   * @generated
   */
  EClass getHoistingActionNew();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.HoistingActionNew#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.HoistingActionNew#getX()
   * @see #getHoistingActionNew()
   * @generated
   */
  EAttribute getHoistingActionNew_X();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.ActionNewX <em>Action New X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action New X</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ActionNewX
   * @generated
   */
  EClass getActionNewX();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.ActionNewX#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ActionNewX#getValue()
   * @see #getActionNewX()
   * @generated
   */
  EAttribute getActionNewX_Value();

  /**
   * Returns the meta object for class '{@link org.eclipse.xtext.astconversion.astConversionSimple.HoistingActionNewX <em>Hoisting Action New X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hoisting Action New X</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.HoistingActionNewX
   * @generated
   */
  EClass getHoistingActionNewX();

  /**
   * Returns the meta object for the attribute '{@link org.eclipse.xtext.astconversion.astConversionSimple.HoistingActionNewX#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.HoistingActionNewX#getValue()
   * @see #getHoistingActionNewX()
   * @generated
   */
  EAttribute getHoistingActionNewX_Value();

  /**
   * Returns the meta object for enum '{@link org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind <em>Change Kind</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Change Kind</em>'.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind
   * @generated
   */
  EEnum getChangeKind();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  AstConversionSimpleFactory getAstConversionSimpleFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ProgramImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Entries</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__ENTRIES = eINSTANCE.getProgram_Entries();

    /**
     * The meta object literal for the '<em><b>Sequence</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__SEQUENCE = eINSTANCE.getProgram_Sequence();

    /**
     * The meta object literal for the '<em><b>Returns New</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__RETURNS_NEW = eINSTANCE.getProgram_ReturnsNew();

    /**
     * The meta object literal for the '<em><b>Action New</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__ACTION_NEW = eINSTANCE.getProgram_ActionNew();

    /**
     * The meta object literal for the '<em><b>List</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__LIST = eINSTANCE.getProgram_List();

    /**
     * The meta object literal for the '<em><b>Hoisting Alternative</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__HOISTING_ALTERNATIVE = eINSTANCE.getProgram_HoistingAlternative();

    /**
     * The meta object literal for the '<em><b>Hoisting Action New</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__HOISTING_ACTION_NEW = eINSTANCE.getProgram_HoistingActionNew();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.EntryImpl <em>Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.EntryImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getEntry()
     * @generated
     */
    EClass ENTRY = eINSTANCE.getEntry();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTRY__NAME = eINSTANCE.getEntry_Name();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.AutoClassImpl <em>Auto Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AutoClassImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getAutoClass()
     * @generated
     */
    EClass AUTO_CLASS = eINSTANCE.getAutoClass();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTO_CLASS__REF = eINSTANCE.getAutoClass_Ref();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.AutoExplicitClassImpl <em>Auto Explicit Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AutoExplicitClassImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getAutoExplicitClass()
     * @generated
     */
    EClass AUTO_EXPLICIT_CLASS = eINSTANCE.getAutoExplicitClass();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AUTO_EXPLICIT_CLASS__REF = eINSTANCE.getAutoExplicitClass_Ref();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ManualClassImpl <em>Manual Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ManualClassImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getManualClass()
     * @generated
     */
    EClass MANUAL_CLASS = eINSTANCE.getManualClass();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANUAL_CLASS__REF = eINSTANCE.getManualClass_Ref();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.CustomASTClassImpl <em>Custom AST Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.CustomASTClassImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getCustomASTClass()
     * @generated
     */
    EClass CUSTOM_AST_CLASS = eINSTANCE.getCustomASTClass();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTOM_AST_CLASS__REF = eINSTANCE.getCustomASTClass_Ref();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.CustomCopyASTClassImpl <em>Custom Copy AST Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.CustomCopyASTClassImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getCustomCopyASTClass()
     * @generated
     */
    EClass CUSTOM_COPY_AST_CLASS = eINSTANCE.getCustomCopyASTClass();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUSTOM_COPY_AST_CLASS__REF = eINSTANCE.getCustomCopyASTClass_Ref();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ReferenceImpl <em>Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ReferenceImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getReference()
     * @generated
     */
    EClass REFERENCE = eINSTANCE.getReference();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REFERENCE__NAME = eINSTANCE.getReference_Name();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.OtherImpl <em>Other</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.OtherImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getOther()
     * @generated
     */
    EClass OTHER = eINSTANCE.getOther();

    /**
     * The meta object literal for the '<em><b>Content</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OTHER__CONTENT = eINSTANCE.getOther_Content();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ElementImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__TYPE = eINSTANCE.getElement_Type();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ELEMENT__VALUE = eINSTANCE.getElement_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.SequenceImpl <em>Sequence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.SequenceImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getSequence()
     * @generated
     */
    EClass SEQUENCE = eINSTANCE.getSequence();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SEQUENCE__EXPRESSIONS = eINSTANCE.getSequence_Expressions();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AdditionImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ReturnsNewXImpl <em>Returns New X</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ReturnsNewXImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getReturnsNewX()
     * @generated
     */
    EClass RETURNS_NEW_X = eINSTANCE.getReturnsNewX();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RETURNS_NEW_X__VALUE = eINSTANCE.getReturnsNewX_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ActionNewImpl <em>Action New</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ActionNewImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getActionNew()
     * @generated
     */
    EClass ACTION_NEW = eINSTANCE.getActionNew();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ListsImpl <em>Lists</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ListsImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getLists()
     * @generated
     */
    EClass LISTS = eINSTANCE.getLists();

    /**
     * The meta object literal for the '<em><b>A</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTS__A = eINSTANCE.getLists_A();

    /**
     * The meta object literal for the '<em><b>B</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTS__B = eINSTANCE.getLists_B();

    /**
     * The meta object literal for the '<em><b>C</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTS__C = eINSTANCE.getLists_C();

    /**
     * The meta object literal for the '<em><b>D</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTS__D = eINSTANCE.getLists_D();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.MapEntryImpl <em>Map Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.MapEntryImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getMapEntry()
     * @generated
     */
    EClass MAP_ENTRY = eINSTANCE.getMapEntry();

    /**
     * The meta object literal for the '<em><b>Keys</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAP_ENTRY__KEYS = eINSTANCE.getMapEntry_Keys();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAP_ENTRY__VALUE = eINSTANCE.getMapEntry_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.MapEntryCustomImpl <em>Map Entry Custom</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.MapEntryCustomImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getMapEntryCustom()
     * @generated
     */
    EClass MAP_ENTRY_CUSTOM = eINSTANCE.getMapEntryCustom();

    /**
     * The meta object literal for the '<em><b>Keys</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAP_ENTRY_CUSTOM__KEYS = eINSTANCE.getMapEntryCustom_Keys();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAP_ENTRY_CUSTOM__VALUE = eINSTANCE.getMapEntryCustom_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingAlternativeImpl <em>Hoisting Alternative</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingAlternativeImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getHoistingAlternative()
     * @generated
     */
    EClass HOISTING_ALTERNATIVE = eINSTANCE.getHoistingAlternative();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOISTING_ALTERNATIVE__VAL = eINSTANCE.getHoistingAlternative_Val();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.XImpl <em>X</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.XImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getX()
     * @generated
     */
    EClass X = eINSTANCE.getX();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.YImpl <em>Y</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.YImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getY()
     * @generated
     */
    EClass Y = eINSTANCE.getY();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute Y__Y = eINSTANCE.getY_Y();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingActionNewImpl <em>Hoisting Action New</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingActionNewImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getHoistingActionNew()
     * @generated
     */
    EClass HOISTING_ACTION_NEW = eINSTANCE.getHoistingActionNew();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOISTING_ACTION_NEW__X = eINSTANCE.getHoistingActionNew_X();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.ActionNewXImpl <em>Action New X</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.ActionNewXImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getActionNewX()
     * @generated
     */
    EClass ACTION_NEW_X = eINSTANCE.getActionNewX();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION_NEW_X__VALUE = eINSTANCE.getActionNewX_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingActionNewXImpl <em>Hoisting Action New X</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.HoistingActionNewXImpl
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getHoistingActionNewX()
     * @generated
     */
    EClass HOISTING_ACTION_NEW_X = eINSTANCE.getHoistingActionNewX();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HOISTING_ACTION_NEW_X__VALUE = eINSTANCE.getHoistingActionNewX_Value();

    /**
     * The meta object literal for the '{@link org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind <em>Change Kind</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind
     * @see org.eclipse.xtext.astconversion.astConversionSimple.impl.AstConversionSimplePackageImpl#getChangeKind()
     * @generated
     */
    EEnum CHANGE_KIND = eINSTANCE.getChangeKind();

  }

} //AstConversionSimplePackage
