/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Auto Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.AutoClass#getRef1 <em>Ref1</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.AutoClass#getName1 <em>Name1</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getAutoClass()
 * @model
 * @generated
 */
public interface AutoClass extends Entry
{
  /**
   * Returns the value of the '<em><b>Ref1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref1</em>' containment reference.
   * @see #setRef1(Reference)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getAutoClass_Ref1()
   * @model containment="true"
   * @generated
   */
  Reference getRef1();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.AutoClass#getRef1 <em>Ref1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref1</em>' containment reference.
   * @see #getRef1()
   * @generated
   */
  void setRef1(Reference value);

  /**
   * Returns the value of the '<em><b>Name1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name1</em>' attribute.
   * @see #setName1(String)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getAutoClass_Name1()
   * @model
   * @generated
   */
  String getName1();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.AutoClass#getName1 <em>Name1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name1</em>' attribute.
   * @see #getName1()
   * @generated
   */
  void setName1(String value);

} // AutoClass
