/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom Copy AST Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomCopyASTClass#getRef4 <em>Ref4</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomCopyASTClass#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getCustomCopyASTClass()
 * @model
 * @generated
 */
public interface CustomCopyASTClass extends Entry
{
  /**
   * Returns the value of the '<em><b>Ref4</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref4</em>' containment reference.
   * @see #setRef4(Reference)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getCustomCopyASTClass_Ref4()
   * @model containment="true"
   * @generated
   */
  Reference getRef4();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomCopyASTClass#getRef4 <em>Ref4</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref4</em>' containment reference.
   * @see #getRef4()
   * @generated
   */
  void setRef4(Reference value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getCustomCopyASTClass_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomCopyASTClass#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // CustomCopyASTClass
