/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom AST Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass#getRef <em>Ref</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getCustomASTClass()
 * @model
 * @generated
 */
public interface CustomASTClass extends Entry
{
  /**
   * Returns the value of the '<em><b>Ref</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref</em>' containment reference.
   * @see #setRef(Reference)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getCustomASTClass_Ref()
   * @model containment="true"
   * @generated
   */
  Reference getRef();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass#getRef <em>Ref</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref</em>' containment reference.
   * @see #getRef()
   * @generated
   */
  void setRef(Reference value);

} // CustomASTClass
