/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Custom AST Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass#getRef4 <em>Ref4</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass#getName4 <em>Name4</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getCustomASTClass()
 * @model
 * @generated
 */
public interface CustomASTClass extends Entry
{
  /**
   * Returns the value of the '<em><b>Ref4</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref4</em>' containment reference.
   * @see #setRef4(Reference)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getCustomASTClass_Ref4()
   * @model containment="true"
   * @generated
   */
  Reference getRef4();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass#getRef4 <em>Ref4</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref4</em>' containment reference.
   * @see #getRef4()
   * @generated
   */
  void setRef4(Reference value);

  /**
   * Returns the value of the '<em><b>Name4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name4</em>' attribute.
   * @see #setName4(String)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getCustomASTClass_Name4()
   * @model
   * @generated
   */
  String getName4();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass#getName4 <em>Name4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name4</em>' attribute.
   * @see #getName4()
   * @generated
   */
  void setName4(String value);

} // CustomASTClass
