/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Element#getType <em>Type</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Element#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getElement()
 * @model
 * @generated
 */
public interface Element extends Entry
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind
   * @see #setType(ChangeKind)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getElement_Type()
   * @model
   * @generated
   */
  ChangeKind getType();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.Element#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind
   * @see #getType()
   * @generated
   */
  void setType(ChangeKind value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute list.
   * The list contents are of type {@link org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind}.
   * The literals are from the enumeration {@link org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute list.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.ChangeKind
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getElement_Value()
   * @model unique="false"
   * @generated
   */
  EList<ChangeKind> getValue();

} // Element
