/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Manual Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.ManualClass#getRef3 <em>Ref3</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.ManualClass#getName3 <em>Name3</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getManualClass()
 * @model
 * @generated
 */
public interface ManualClass extends Entry
{
  /**
   * Returns the value of the '<em><b>Ref3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref3</em>' containment reference.
   * @see #setRef3(Reference)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getManualClass_Ref3()
   * @model containment="true"
   * @generated
   */
  Reference getRef3();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.ManualClass#getRef3 <em>Ref3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref3</em>' containment reference.
   * @see #getRef3()
   * @generated
   */
  void setRef3(Reference value);

  /**
   * Returns the value of the '<em><b>Name3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name3</em>' attribute.
   * @see #setName3(String)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getManualClass_Name3()
   * @model
   * @generated
   */
  String getName3();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.ManualClass#getName3 <em>Name3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name3</em>' attribute.
   * @see #getName3()
   * @generated
   */
  void setName3(String value);

} // ManualClass
