/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Other</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Other#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getOther()
 * @model
 * @generated
 */
public interface Other extends Entry
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' containment reference.
   * @see #setContent(EObject)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getOther_Content()
   * @model containment="true"
   * @generated
   */
  EObject getContent();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.Other#getContent <em>Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Content</em>' containment reference.
   * @see #getContent()
   * @generated
   */
  void setContent(EObject value);

} // Other
