/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getEntries <em>Entries</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getSequence <em>Sequence</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getReturnsNew <em>Returns New</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getActionNew <em>Action New</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getList <em>List</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Entries</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.astconversion.astConversionSimple.Entry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entries</em>' containment reference list.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getProgram_Entries()
   * @model containment="true"
   * @generated
   */
  EList<Entry> getEntries();

  /**
   * Returns the value of the '<em><b>Sequence</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.astconversion.astConversionSimple.Sequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequence</em>' containment reference list.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getProgram_Sequence()
   * @model containment="true"
   * @generated
   */
  EList<Sequence> getSequence();

  /**
   * Returns the value of the '<em><b>Returns New</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Returns New</em>' containment reference.
   * @see #setReturnsNew(ReturnsNewX)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getProgram_ReturnsNew()
   * @model containment="true"
   * @generated
   */
  ReturnsNewX getReturnsNew();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getReturnsNew <em>Returns New</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Returns New</em>' containment reference.
   * @see #getReturnsNew()
   * @generated
   */
  void setReturnsNew(ReturnsNewX value);

  /**
   * Returns the value of the '<em><b>Action New</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action New</em>' containment reference.
   * @see #setActionNew(ActionNew)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getProgram_ActionNew()
   * @model containment="true"
   * @generated
   */
  ActionNew getActionNew();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getActionNew <em>Action New</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action New</em>' containment reference.
   * @see #getActionNew()
   * @generated
   */
  void setActionNew(ActionNew value);

  /**
   * Returns the value of the '<em><b>List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' containment reference.
   * @see #setList(Lists)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getProgram_List()
   * @model containment="true"
   * @generated
   */
  Lists getList();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getList <em>List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' containment reference.
   * @see #getList()
   * @generated
   */
  void setList(Lists value);

} // Program
