/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getEntries <em>Entries</em>}</li>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Program#getSequence <em>Sequence</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getProgram()
 * @model
 * @generated
 */
public interface Program extends EObject
{
  /**
   * Returns the value of the '<em><b>Entries</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.astconversion.astConversionSimple.Entry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entries</em>' containment reference list.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getProgram_Entries()
   * @model containment="true"
   * @generated
   */
  EList<Entry> getEntries();

  /**
   * Returns the value of the '<em><b>Sequence</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.xtext.astconversion.astConversionSimple.Sequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequence</em>' containment reference list.
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getProgram_Sequence()
   * @model containment="true"
   * @generated
   */
  EList<Sequence> getSequence();

} // Program
