/**
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.astConversionSimple;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Y</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.xtext.astconversion.astConversionSimple.Y#getY <em>Y</em>}</li>
 * </ul>
 *
 * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getY()
 * @model
 * @generated
 */
public interface Y extends HoistingAlternative
{
  /**
   * Returns the value of the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Y</em>' attribute.
   * @see #setY(String)
   * @see org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage#getY_Y()
   * @model
   * @generated
   */
  String getY();

  /**
   * Sets the value of the '{@link org.eclipse.xtext.astconversion.astConversionSimple.Y#getY <em>Y</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Y</em>' attribute.
   * @see #getY()
   * @generated
   */
  void setY(String value);

} // Y
