/*
 * generated by Xtext
 */
package org.eclipse.xtext.astconversion.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.astconversion.astConversionSimple.AstConversionSimplePackage;
import org.eclipse.xtext.astconversion.astConversionSimple.AutoClass;
import org.eclipse.xtext.astconversion.astConversionSimple.AutoExplicitClass;
import org.eclipse.xtext.astconversion.astConversionSimple.CustomASTClass;
import org.eclipse.xtext.astconversion.astConversionSimple.CustomCopyASTClass;
import org.eclipse.xtext.astconversion.astConversionSimple.ManualClass;
import org.eclipse.xtext.astconversion.astConversionSimple.Program;
import org.eclipse.xtext.astconversion.astConversionSimple.Reference;
import org.eclipse.xtext.astconversion.services.ASTConversionSimpleGrammarAccess;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class ASTConversionSimpleSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ASTConversionSimpleGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == AstConversionSimplePackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case AstConversionSimplePackage.AUTO_CLASS:
				sequence_AutoClass(context, (AutoClass) semanticObject); 
				return; 
			case AstConversionSimplePackage.AUTO_EXPLICIT_CLASS:
				sequence_AutoExplicitClass(context, (AutoExplicitClass) semanticObject); 
				return; 
			case AstConversionSimplePackage.CUSTOM_AST_CLASS:
				sequence_CustomASTClass(context, (CustomASTClass) semanticObject); 
				return; 
			case AstConversionSimplePackage.CUSTOM_COPY_AST_CLASS:
				sequence_CustomCopyASTClass(context, (CustomCopyASTClass) semanticObject); 
				return; 
			case AstConversionSimplePackage.MANUAL_CLASS:
				sequence_ManualClass(context, (ManualClass) semanticObject); 
				return; 
			case AstConversionSimplePackage.PROGRAM:
				sequence_Program(context, (Program) semanticObject); 
				return; 
			case AstConversionSimplePackage.REFERENCE:
				sequence_Reference(context, (Reference) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Entry returns AutoClass
	 *     AutoClass returns AutoClass
	 *
	 * Constraint:
	 *     (ref1=Reference name1=ID)
	 */
	protected void sequence_AutoClass(ISerializationContext context, AutoClass semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.AUTO_CLASS__REF1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.AUTO_CLASS__REF1));
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.AUTO_CLASS__NAME1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.AUTO_CLASS__NAME1));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAutoClassAccess().getRef1ReferenceParserRuleCall_1_0(), semanticObject.getRef1());
		feeder.accept(grammarAccess.getAutoClassAccess().getName1IDTerminalRuleCall_2_0(), semanticObject.getName1());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Entry returns AutoExplicitClass
	 *     AutoExplicitClass returns AutoExplicitClass
	 *
	 * Constraint:
	 *     (ref2=Reference name2=ID)
	 */
	protected void sequence_AutoExplicitClass(ISerializationContext context, AutoExplicitClass semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.AUTO_EXPLICIT_CLASS__REF2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.AUTO_EXPLICIT_CLASS__REF2));
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.AUTO_EXPLICIT_CLASS__NAME2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.AUTO_EXPLICIT_CLASS__NAME2));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAutoExplicitClassAccess().getRef2ReferenceParserRuleCall_1_0(), semanticObject.getRef2());
		feeder.accept(grammarAccess.getAutoExplicitClassAccess().getName2IDTerminalRuleCall_2_0(), semanticObject.getName2());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Entry returns CustomASTClass
	 *     CustomASTClass returns CustomASTClass
	 *
	 * Constraint:
	 *     (ref4=Reference name4=ID)
	 */
	protected void sequence_CustomASTClass(ISerializationContext context, CustomASTClass semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.CUSTOM_AST_CLASS__REF4) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.CUSTOM_AST_CLASS__REF4));
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.CUSTOM_AST_CLASS__NAME4) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.CUSTOM_AST_CLASS__NAME4));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCustomASTClassAccess().getRef4ReferenceParserRuleCall_1_0(), semanticObject.getRef4());
		feeder.accept(grammarAccess.getCustomASTClassAccess().getName4IDTerminalRuleCall_2_0(), semanticObject.getName4());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Entry returns CustomCopyASTClass
	 *     CustomCopyASTClass returns CustomCopyASTClass
	 *
	 * Constraint:
	 *     (ref4=Reference name=ID)
	 */
	protected void sequence_CustomCopyASTClass(ISerializationContext context, CustomCopyASTClass semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.CUSTOM_COPY_AST_CLASS__REF4) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.CUSTOM_COPY_AST_CLASS__REF4));
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.CUSTOM_COPY_AST_CLASS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.CUSTOM_COPY_AST_CLASS__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCustomCopyASTClassAccess().getRef4ReferenceParserRuleCall_1_0(), semanticObject.getRef4());
		feeder.accept(grammarAccess.getCustomCopyASTClassAccess().getNameIDTerminalRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Entry returns ManualClass
	 *     ManualClass returns ManualClass
	 *
	 * Constraint:
	 *     (ref3=Reference name3=ID)
	 */
	protected void sequence_ManualClass(ISerializationContext context, ManualClass semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.MANUAL_CLASS__REF3) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.MANUAL_CLASS__REF3));
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.MANUAL_CLASS__NAME3) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.MANUAL_CLASS__NAME3));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getManualClassAccess().getRef3ReferenceParserRuleCall_1_0(), semanticObject.getRef3());
		feeder.accept(grammarAccess.getManualClassAccess().getName3IDTerminalRuleCall_2_0(), semanticObject.getName3());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Program returns Program
	 *
	 * Constraint:
	 *     entries+=Entry+
	 */
	protected void sequence_Program(ISerializationContext context, Program semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Reference returns Reference
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Reference(ISerializationContext context, Reference semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, AstConversionSimplePackage.Literals.REFERENCE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, AstConversionSimplePackage.Literals.REFERENCE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getReferenceAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
}
